# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LSAFN' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LSAFN

# 网络请求
pod 'AFNetworking'

end
